apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress-dev
  namespace: playpal-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dev-playpal.lzainzinger.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service-dev
            port:
              number: 80
