apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-deployment-dev
  namespace: playpal-dev
  labels:
    app: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: matching-service
          image: YOUR_DOCKER_REGISTRY/playpal-matching-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_USER
              value: "playpal_user"
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongo-password
            - name: MONGODB_HOST
              value: "mongodb"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: "playpal"
            - name: MONGODB_URI
              value: "mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@$(MONGODB_HOST):$(MONGODB_PORT)/$(MONGODB_DATABASE)?authSource=$(MONGODB_DATABASE)"
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: kafka-dev-credentials
                  key: KAFKA_BROKERS
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-dev-credentials
                  key: KAFKA_SASL_USERNAME
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-dev-credentials
                  key: KAFKA_SASL_PASSWORD
            - name: KAFKA_SSL_CA
              valueFrom:
                secretKeyRef:
                  name: kafka-dev-credentials
                  key: KAFKA_CA_CERTIFICATE
            - name: KAFKA_TOPIC
              value: "matches.matched.dev"
