apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: playpal-dev
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: notification-service
          image: YOUR_DOCKER_REGISTRY/playpal-notification-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: kafka-dev-credentials
                  key: KAFKA_BROKERS
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-dev-credentials
                  key: KAFKA_SASL_USERNAME
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-dev-credentials
                  key: KAFKA_SASL_PASSWORD
            - name: KAFKA_SSL_CA
              valueFrom:
                secretKeyRef:
                  name: kafka-dev-credentials
                  key: KAFKA_CA_CERTIFICATE
            - name: KAFKA_TOPIC
              value: "matches.matched.dev"
            - name: NODE_ENV
              value: "development"