replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: "6.0"

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  storageClass: "exoscale-sbs"
  size: 8Gi

auth:
  enabled: true
  rootUsername: root
  # rootPassword will be generated if not provided
  database: playpal
  username: playpal_user
  # password will be generated if not provided
